version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .

  build:
    commands:
      # Copy app code into current directory (root of artifact)
      - cp *.py .
      - cp -r scripts .

artifacts:
  files:
    - '**/*'
