version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - cp -r * package/
      - cd package
      - zip -r ../user-management.zip .
artifacts:
  files:
    - user-management.zip
