version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - echo "Packaging application code..."
      - mkdir -p package
      # Copy all Python files from root and scripts/
      - cp *.py package/
      - cp -r scripts/* package/
      - cd package
      - zip -r ../user-management.zip .

  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -lh ../user-management.zip

artifacts:
  files:
    - user-management.zip
