version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - mkdir -p package
      - pip install -r requirements.txt -t package/

  build:
    commands:
      # Copy app code into package
      - cp *.py package/
      - cp -r scripts package/

artifacts:
  base-directory: package
  files:
    - '**/*'

