version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - sam build              # build SAM template
      - sam package \
          --s3-bucket $DEPLOYMENT_BUCKET \
          --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
cache:
  paths:
    - '/root/.cache/pip/**/*'
